// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: tunnel.proto

package tunnel

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TunnelServiceClient is the client API for TunnelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TunnelServiceClient interface {
	GetClientInitiatedTunnels(ctx context.Context, in *TunnelGetPayload, opts ...grpc.CallOption) (*TunnelList, error)
	TunnelChat(ctx context.Context, opts ...grpc.CallOption) (TunnelService_TunnelChatClient, error)
}

type tunnelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTunnelServiceClient(cc grpc.ClientConnInterface) TunnelServiceClient {
	return &tunnelServiceClient{cc}
}

func (c *tunnelServiceClient) GetClientInitiatedTunnels(ctx context.Context, in *TunnelGetPayload, opts ...grpc.CallOption) (*TunnelList, error) {
	out := new(TunnelList)
	err := c.cc.Invoke(ctx, "/tunnel.TunnelService/GetClientInitiatedTunnels", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tunnelServiceClient) TunnelChat(ctx context.Context, opts ...grpc.CallOption) (TunnelService_TunnelChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &TunnelService_ServiceDesc.Streams[0], "/tunnel.TunnelService/TunnelChat", opts...)
	if err != nil {
		return nil, err
	}
	x := &tunnelServiceTunnelChatClient{stream}
	return x, nil
}

type TunnelService_TunnelChatClient interface {
	Send(*TunnelMessage) error
	Recv() (*TunnelMessage, error)
	grpc.ClientStream
}

type tunnelServiceTunnelChatClient struct {
	grpc.ClientStream
}

func (x *tunnelServiceTunnelChatClient) Send(m *TunnelMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *tunnelServiceTunnelChatClient) Recv() (*TunnelMessage, error) {
	m := new(TunnelMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TunnelServiceServer is the server API for TunnelService service.
// All implementations must embed UnimplementedTunnelServiceServer
// for forward compatibility
type TunnelServiceServer interface {
	GetClientInitiatedTunnels(context.Context, *TunnelGetPayload) (*TunnelList, error)
	TunnelChat(TunnelService_TunnelChatServer) error
	mustEmbedUnimplementedTunnelServiceServer()
}

// UnimplementedTunnelServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTunnelServiceServer struct {
}

func (UnimplementedTunnelServiceServer) GetClientInitiatedTunnels(context.Context, *TunnelGetPayload) (*TunnelList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClientInitiatedTunnels not implemented")
}
func (UnimplementedTunnelServiceServer) TunnelChat(TunnelService_TunnelChatServer) error {
	return status.Errorf(codes.Unimplemented, "method TunnelChat not implemented")
}
func (UnimplementedTunnelServiceServer) mustEmbedUnimplementedTunnelServiceServer() {}

// UnsafeTunnelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TunnelServiceServer will
// result in compilation errors.
type UnsafeTunnelServiceServer interface {
	mustEmbedUnimplementedTunnelServiceServer()
}

func RegisterTunnelServiceServer(s grpc.ServiceRegistrar, srv TunnelServiceServer) {
	s.RegisterService(&TunnelService_ServiceDesc, srv)
}

func _TunnelService_GetClientInitiatedTunnels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TunnelGetPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelServiceServer).GetClientInitiatedTunnels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tunnel.TunnelService/GetClientInitiatedTunnels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelServiceServer).GetClientInitiatedTunnels(ctx, req.(*TunnelGetPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _TunnelService_TunnelChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TunnelServiceServer).TunnelChat(&tunnelServiceTunnelChatServer{stream})
}

type TunnelService_TunnelChatServer interface {
	Send(*TunnelMessage) error
	Recv() (*TunnelMessage, error)
	grpc.ServerStream
}

type tunnelServiceTunnelChatServer struct {
	grpc.ServerStream
}

func (x *tunnelServiceTunnelChatServer) Send(m *TunnelMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *tunnelServiceTunnelChatServer) Recv() (*TunnelMessage, error) {
	m := new(TunnelMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TunnelService_ServiceDesc is the grpc.ServiceDesc for TunnelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TunnelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tunnel.TunnelService",
	HandlerType: (*TunnelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClientInitiatedTunnels",
			Handler:    _TunnelService_GetClientInitiatedTunnels_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TunnelChat",
			Handler:       _TunnelService_TunnelChat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "tunnel.proto",
}
